k

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -25,21 +25,18 @@ jobs:
 
     - name: Set up Azure CLI
       run: |
+        echo "Azure CLI version:"
+        az --version
+        echo "Setting up Azure CLI..."
+        echo "Logging in with service principal..."
         az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
-
-    - name: Debug
-      run: |
-         echo "Selected Environment: $ENVIRONMENT"
-         az account show
-         az resource show --ids /subscriptions/$ARM_SUBSCRIPTION_ID/resourceGroups
-
-    - name: Terraform Init
-      run: terraform init
-
-    - name: Terraform Apply
-      run: terraform apply -var-file=terraform.tfvars -auto-approve
-
-    - name: Check Azure CLI version
-      run: az --version
+        if [ $? -eq 0 ]; then
+          echo "Azure CLI login successful."
+          echo "Azure account information:"
+          az account show
+        else
+          echo "Azure CLI login failed."
+          exit 1
+        fi
 
 
